services:
  - type: web
    name: golden-space
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: PORT
        value: 8080
